var wallets = {
	"rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B" : "Bitstamp",
	"rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1" : "Bitstamp hotwallet",
	"rGFuMiw48HdbnrUbkRYuitXTmfrDBNTCnX" : "Bitstamp hot",
	"rLEsXccBGNR3UPuPu2hUXPjziKC3qKSBun" : "RockTrading",
	"rPDXxSZcuVL3ZWoyU82bcde3zwvmShkRyF" : "WirePass",
	"r9xAQUyqs53QH2PLxe7iFbNbpU2RA9QtZx" : "WirePass hotwallet",
	"rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q" : "SnapSwap",
	"rhasPLL5GaXzBh5amQkN7Dr1SNF4Whb2ZT" : "SnapSwap hotwallet",
	"r5ymZSvtdNgbKVc8ay1Jhmq5f9QgnvEtj"  : "SnapSwap-btc-hot",
	"r3ADD8kXSUKHd6zTCKfnKT3zV9EZHjzp1S" : "RippleUnion",
	"rNPRNzBB92BVpAhhZr4iXDTveCgV5Pofm9" : "RippleIsrael",
	"rfYv1TXnwgDDK4WQNbFALykYuEBnrR4pDX" : "DividendRippler",
	"rnuF96W4SZoCJmbHYBFoJZpR8eCaxNvekK" : "RippleCN",
	"rno91tGDJeRcnM7EMXj8KG9UTyxRGMMz8s" : "RippleCN-hot2",
	"rNaptDNfFXo1quhKwMaNPf66iwPqA8YLky" : "RippleCN-hot",
	"rfNNhNeeuXj6vgY31pVu3Ge2DuEDEtgSor" : "RippleCN redeem",
	"rajgeXpN88PNquRcaBXKH7uuVsPMq7aP47" : "RippleCN withdraw",
	"rHiqXXVXNK85UJH7oEB4D81TJhwbH8vyrk" : "RippleCN withdraw2",
	"rfLkDwAEQSpTvShmSLLSGWhMmEk65Va1jR" : "RippleCN Yuhao",
	"rEKbakXJMo4Cnb7WJekVW38mANAMXajAXi" : "RippleTo",
	"razqQKzJRdB4UxFPWf5NEpEG3WMkmwgcXA" : "RippleChina",
	"r45dBj4S3VvMMYXxr9vHX4Z4Ma6ifPMCkK" : "RippleChina hotwallet old",
	"rBXJpRvUWcjY9fQHZAFnENucuiWnqwrvqF" : "RippleChina hotwallet",
	"rGYYWKxT1XgNipUJouCq4cKiyAdq8xBoE9" : "Rippay",
	"rKiCet8SdvWxPXnAgYarFUXMh1zCPz432Y" : "RippleFox",
	"r9Dr5xwkeLegBeXq6ujinjSBLQzQ1zQGjH" : "RippleSingapore",
	"rsYnSWfvcJPpKC1QwDfdLixdk8VNQpAUv5" : "HotXRP",
	"rM8199qFwspxiWNZRChZdZbGN5WrCepVP1" : "XRPChina",
	"rE7CNMbxwvTQrqSEjbcXCrqeN6EZga1ApU" : "RippleFund",
	"rMAz5ZnK73nyNUL4foAvaxdreczCkG3vA6" : "RippleTradeJapan (closed)",
	"r9vbV3EHvXWjSkeQ6CAcYVPGeq7TuiXY2X" : "WeExchange USD",
	"rBcYpuDT1aXNo4jnqczWJTytKGdBGufsre" : "WeExchange AUD",
	"rpvfJ4mR6QQAeogpXEKnuyGBx8mYCSnYZi" : "WeExchange BTC",
	"r47RkFi1Ew3LvCNKT6ufw3ZCyj5AJiLHi9" : "WeExchange CAD",
	"rsP3mgGb2tcYUrxiLFiHJiQXhsziegtwBc" : "Coinex (closed)",
	"ra9eZxMbJrUcgV8ui7aPc161FgrqWScQxV" : "PeerCover (closed)",
	"rfK9co7ypx6DJVDCpNyPr9yGKLNer5GRif" : "PeerCover PCV (closed)",
	"rJHygWcTLVpSXkowott6kzgZU6viQSVYM1" : "Justcoin (closed)",
	"rPKSvQ1qFAksr7hzk2wC2xtqSqFbxP3wvg" : "NoFiatCoin (closed)",
	"rFLiPGytDEwC5heoqFcFAZoqPPmKBzX1o" :  "Rippleflip hotwallet",
	"rHWPTbajsPaSJ1FepcgNNx4FjyghukNBfi" : "BTC38",
	"rMMWFA9TkQ9bpJCadDfCpbHcS79Y7GyP3k" : "BTC38 hot",
	"rfKeuNcxyuKRK8QH5VmcxKfsVgPdSxwGpj" : "BTC38 XRP hotwallet",
	"rfqoQbdhrUtWmWzpwzHPD26ZX5Vejz6DsK" : "BTC38 XRP send",
	"rHWPTbajsPaSJ1FepcgNNx4FjyghukNBfi" : "BTC38 CNY ripplechina",
	"rpJrC46bPSUiWwTuuRGSiqHdSaCNWTFBZv" : "JuBi.com",
	"rrh7rf1gV2pXAoqA8oYbpHd8TKv5ZQeo67" : "GBI",
	"r94s8px6kSw1uZ1MV98dhSRTvc6VMPoPcN" : "TokyoJPY",
	"r9ZFPSb1TFdnJwbTMYHvVwFK1bQPUCVNfJ" : "ExchangeTokyo",
	"rUMzD7LmqHSKm9j6aSfxj1ojzdDgLvDxXf" : "ExchangeTokyo Hub",
	"rJRi8WW24gt9X85PHAxfWNPCizMMhqUQwg" : "MarketJapan",
	"rUkMKjQitpgAM5WTGk79xpjT38DEJY283d" : "PaxMoneta",
	"rDVdJ62foD1sn7ZpxtXyptdkBSyhsQGviT" : "RippleDividend",
	
	"GCLDH6L6FBLTD3H3B23D6TIFVVTFBLZMNBC3ZOI6FGI5GPQROL4FOXIN" : "RippleFox XLM IN",
	"GCGNWKCJ3KHRLPM3TM6N7D3W5YKDJFL6A2YCXFXNMRTZ4Q66MEMZ6FI2" : "Poloniex XLM"
}

var fiat = [ 'USD', 'EUR', 'JPY', 'CNY', 'INR', 'RUB', 'GBP', 'CAD', 'BRL',
		'CHF', 'DKK', 'SEK', 'CZK', 'PLN', 'AUD', 'MXN', 'KRW', 'TWD', 'HKD',
		'KES', 'AMD', 'RUR', 'RON', 'NZD', 'TRY' ];

function isFiat(curr) {
	return fiat.indexOf(curr) > -1 ? true : false;
}
